#==============================================================================#
# SwiftLint Rules
#==============================================================================#

#==============================================================================#
# Included & Excluded
#==============================================================================#
excluded:
  - Carthage
  - Pods
  - Package.swift

#==============================================================================#
# Disabled Rules
#==============================================================================#
disabled_rules:
- block_based_kvo
- compiler_protocol_init
- computed_accessors_order
- control_statement
- custom_rules
- cyclomatic_complexity
- deployment_target
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- duplicated_key_in_dictionary_literal
- dynamic_inline
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- for_where
- function_body_length
- function_parameter_count
- generic_type_name
- implicit_getter
- inclusive_language
- is_disjoint
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_nsgeometry_functions
- legacy_random
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- ns_number_init_as_function_reference
- nsobject_prefer_isequal
- opening_brace
- operator_whitespace
- orphaned_doc_comment
- private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order
- reduce_boolean
- redundant_discardable_let
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- self_in_property_initialization
- shorthand_operator
- statement_position
- superfluous_disable_command
- switch_case_alignment
- syntactic_sugar
- trailing_comma
- trailing_semicolon
- unavailable_condition
- unneeded_break_in_switch
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- void_function_in_ternary
- void_return
- xctfail_message
- class_delegate_protocol
- closing_brace
- closure_parameter_position
- colon
- comma
- mark
- comment_spacing
- todo
- force_cast
- force_try
- line_length
- type_body_length
- file_length
- identifier_name
- type_name

#==============================================================================#
# Opt-in Rules
# Find all the available rules by running: `swiftlint rules`
#==============================================================================#
# opt_in_rules:
#   - empty_count

#==============================================================================#
# Analyzer Rules
# Rules run by `swiftlint analyze`
#==============================================================================#
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

#==============================================================================#
# Type Name
#==============================================================================#
# type_name:
#   min_length: 4
#   max_length:
#     warning: 40
#     error: 50
#   excluded:
#     - iPhone
#   allowed_symbols: ["_"]

#==============================================================================#
# Identifier Name
#==============================================================================#
# identifier_name:
#   min_length:
#     error: 4
#   excluded:
#     - id
#     - db
#     - URL

#==============================================================================#
# Line/File Length
#==============================================================================#
# line_length: 110
# type_body_length:
#   - warning: 300
#   - error: 400
# file_length:
#   warning: 500
#   error: 1200

#==============================================================================#
# Other Rules
#==============================================================================#
# force_cast: warning
# force_try:
#   severity: warning
